### ISSUE TITLE
Restore (new window) just opens one empty tab

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [ReDEnergy/SessionSync#34]
Restore (new window) just opens one empty tab and restores nothing

**Comment by ReDEnergy** [comment]
I will assume that by **Restore (new Window)** action you are referring to the session restore and not bookmark context menu where the text is **Open (new Window)**.
Now... I really don't know why that is happening, it should definitely not be a problem unless there are a few specific unsupported URLs (by Firefox itself and I can't do a thing about it)

```
For security reasons, in Firefox, this may not be a privileged URL. So passing any of the following URLs will fail:
chrome: URLs
javascript: URLs
data: URLs
file: URLs (i.e., files on the filesystem. However, to use a file packaged inside the extension, see below)
privileged about: URLs (for example, about:config, about:addons, about:debugging). Non-privileged URLs (e.g., about:blank) are allowed.
The New Tab page (about:newtab) can be opened if no value for URL is provided.
```
Can you please confirm that the list of tabs from that sessions is not made of those kind of link? Because that's the only reason I could possible thing where it will fail to open the tabs at it should and there will only be a visible **empty tab**

**Comment by c-e-p-x-u-o** [comment]
No, just one-three simple urls like google.com.

**Comment by ReDEnergy** [comment]
I will have to investigate this further. I can't really figure out why since it works for me 100% of the time, on different devices so there might be some specific conditions that I can't replicate right now.

There are 2 things that might help me figure this out.
1. If you can provide me (in private) the list of link (only if they are generic links and you do not consider them to create any privacy issues) - that's up to you
2. Tell me if this is happening for all kinds of sessions no matter what is stored there.
  - just save a tab with google.com or whatever for example and try to restore it
  - try with other sessions the same thing.

Other than that... I will try various ideas to see if I will be able to generate the same issues.

**Comment by c-e-p-x-u-o** [comment]
% firefox -ProfileManager -no-remote
create new profile
open https://addons.mozilla.org/en-US/firefox/addon/session-sync/?src=search
add to firefox
optionally open another tab google.com but not mandatory
press
"Session Sync" button
"Save session" button
"Restore in new window" button
a new window with one blank tab appears

just "Restore" adds two tabs

59.0.2-1 (64-bit) debian sid

**Comment by ReDEnergy** [comment]
I imagine the problem is 100% real for you since you even created a profile to test that... but as I try to do the same, It's simply not happening to me. 
I tried on both Firefox 59 and Firefox 60 but only on Windows. Now I'm wondering if there might be a bug in the Linux version in the API itself. I will try to test on a Linux machine as well to be sure about that. I can't see any reason why the code might work for some and not for others, unless there's a specific bug related to the platform OS.

**Comment by c-e-p-x-u-o** [comment]
Just tested, it works on windows (in kvm).

**Comment by ReDEnergy** [comment]
=)) you beat me to it. Was just installing virtual box right know to test it also. Will confirm as well as soon as I can replicate the behavior under Ubuntu. At least we have a starting point, now.
Thanks a lot for being so helpful with tracking the bug. If there's something I can do about it I will try to fix it as soon as possible.

**Comment by c-e-p-x-u-o** [comment]
Just got Fedora-Workstation-Live-x86_64-27-1.6.iso and run in under vbox --- same problem

**Comment by ReDEnergy** [comment]
Ok... I can definitely see a pattern. As soon as I have a working copy of my development workflow to check the output errors I will try to see what solution I can find.

**Comment by ReDEnergy** [comment]
Confirmed as well under Ubuntu... but it's clearly something wrong with the API I think, or the way the panel works.
As you probably know (if not you can try) the addon offers a detach mode
![image](https://user-images.githubusercontent.com/1395510/38650030-56b63ff2-3e02-11e8-8ad3-f7c03c7ed433.png)
If you detach the UI into a separate window or a tab (you can configure that in options) then the **restore new window** action works as it should.
From the panel I get a strange API error, will have to look into it to know if I can find a solution or if there's already a bug issue tracked by Mozilla regarding this.
Until a fix will be available (either from me or if it's an API fault then can't be sure when or if I can find a workaround for it) your have 2 options:
 - create a new window and then access the Session-Sync local restore
 - access the restore function from a detach mode (either as a tab or as a window)

Again, thanks a lot for reporting the issue and helping me to confirm it. I will try to provide a fix as soon as possible.

**Comment by c-e-p-x-u-o** [comment]
Thank you for details. But really I don't use this extension due to #21.

**Comment by ReDEnergy** [comment]
If everything goes by the plan that feature will be implemented into the update as well. Just started myself to use containers more and I can definitely see them as a must have feature now.

**Comment by c-e-p-x-u-o** [comment]
(:

**Comment by ReDEnergy** [comment]
This one should be fixed. A test release is avaiable [here](https://www.dropbox.com/s/u18l8zuzyd4wdbq/session_sync-2.5.2.xpi?dl=0). In a few days the update will be ready on addons.mozilla.org.
#21 is still work in progress

**Comment by c-e-p-x-u-o** [comment]
Not fixed!

Works some time and some time later become broken again.

**Comment by ReDEnergy** [comment]
I think that it's actually fixed, but in my stupidity I set the version 2.5.2 to the above release and the oficial one is 3.0.0 so it will be overwritten by the official Firefox Update version. You can confirm the version in the addon manager -> addon page. Mine was updated as well, so I think this is the problem.

**Comment by c-e-p-x-u-o** [comment]
![qwe](https://user-images.githubusercontent.com/14617699/39135946-ca2c5a2e-4722-11e8-887a-cf0825763960.png)

**Comment by ReDEnergy** [comment]
Definetely fixed in [Version 3.0.1](https://www.dropbox.com/s/n5stbwi2zh9vm1a/session_sync-3.0.1beta.xpi?dl=0)
Also I fixed #38 as well as #37
This one will not be updated to the release version since it's version is higher.
Later today I will try to make an official release (it will be updated automatically and you should see no difference)

**Comment by ReDEnergy** [comment]
Fixed in version 3.0.1 - 544850e
Release available on [AMO](https://addons.mozilla.org/en-US/firefox/addon/session-sync/)
